namespace LVGLSharp.Interop
{
    public enum lv_obj_flag_t : uint
    {
        LV_OBJ_FLAG_HIDDEN = (1U << 0),
        LV_OBJ_FLAG_CLICKABLE = (1U << 1),
        LV_OBJ_FLAG_CLICK_FOCUSABLE = (1U << 2),
        LV_OBJ_FLAG_CHECKABLE = (1U << 3),
        LV_OBJ_FLAG_SCROLLABLE = (1U << 4),
        LV_OBJ_FLAG_SCROLL_ELASTIC = (1U << 5),
        LV_OBJ_FLAG_SCROLL_MOMENTUM = (1U << 6),
        LV_OBJ_FLAG_SCROLL_ONE = (1U << 7),
        LV_OBJ_FLAG_SCROLL_CHAIN_HOR = (1U << 8),
        LV_OBJ_FLAG_SCROLL_CHAIN_VER = (1U << 9),
        LV_OBJ_FLAG_SCROLL_CHAIN = (LV_OBJ_FLAG_SCROLL_CHAIN_HOR | LV_OBJ_FLAG_SCROLL_CHAIN_VER),
        LV_OBJ_FLAG_SCROLL_ON_FOCUS = (1U << 10),
        LV_OBJ_FLAG_SCROLL_WITH_ARROW = (1U << 11),
        LV_OBJ_FLAG_SNAPPABLE = (1U << 12),
        LV_OBJ_FLAG_PRESS_LOCK = (1U << 13),
        LV_OBJ_FLAG_EVENT_BUBBLE = (1U << 14),
        LV_OBJ_FLAG_GESTURE_BUBBLE = (1U << 15),
        LV_OBJ_FLAG_ADV_HITTEST = (1U << 16),
        LV_OBJ_FLAG_IGNORE_LAYOUT = (1U << 17),
        LV_OBJ_FLAG_FLOATING = (1U << 18),
        LV_OBJ_FLAG_SEND_DRAW_TASK_EVENTS = (1U << 19),
        LV_OBJ_FLAG_OVERFLOW_VISIBLE = (1U << 20),
        LV_OBJ_FLAG_EVENT_TRICKLE = (1U << 21),
        LV_OBJ_FLAG_STATE_TRICKLE = (1U << 22),
        LV_OBJ_FLAG_LAYOUT_1 = (1U << 23),
        LV_OBJ_FLAG_LAYOUT_2 = (1U << 24),
        LV_OBJ_FLAG_FLEX_IN_NEW_TRACK = LV_OBJ_FLAG_LAYOUT_1,
        LV_OBJ_FLAG_WIDGET_1 = (1U << 25),
        LV_OBJ_FLAG_WIDGET_2 = (1U << 26),
        LV_OBJ_FLAG_USER_1 = (1U << 27),
        LV_OBJ_FLAG_USER_2 = (1U << 28),
        LV_OBJ_FLAG_USER_3 = (1U << 29),
        LV_OBJ_FLAG_USER_4 = (1U << 30),
    }
}
