namespace LVGLSharp.Interop
{
    public enum lv_screen_load_anim_t
    {
        LV_SCREEN_LOAD_ANIM_NONE,
        LV_SCREEN_LOAD_ANIM_OVER_LEFT,
        LV_SCREEN_LOAD_ANIM_OVER_RIGHT,
        LV_SCREEN_LOAD_ANIM_OVER_TOP,
        LV_SCREEN_LOAD_ANIM_OVER_BOTTOM,
        LV_SCREEN_LOAD_ANIM_MOVE_LEFT,
        LV_SCREEN_LOAD_ANIM_MOVE_RIGHT,
        LV_SCREEN_LOAD_ANIM_MOVE_TOP,
        LV_SCREEN_LOAD_ANIM_MOVE_BOTTOM,
        LV_SCREEN_LOAD_ANIM_FADE_IN,
        LV_SCREEN_LOAD_ANIM_FADE_ON = LV_SCREEN_LOAD_ANIM_FADE_IN,
        LV_SCREEN_LOAD_ANIM_FADE_OUT,
        LV_SCREEN_LOAD_ANIM_OUT_LEFT,
        LV_SCREEN_LOAD_ANIM_OUT_RIGHT,
        LV_SCREEN_LOAD_ANIM_OUT_TOP,
        LV_SCREEN_LOAD_ANIM_OUT_BOTTOM,
    }
}
